article/urls.py
from django.conf.urls import patterns, include, url
<<<<<<< HEAD
from api import ArticleResource

article_resource = ArticleResource()

=======
>>>>>>> 347f063cefe0b889c1543b457ddb9de550edb957

urlpatterns = patterns('',
    url(r'^all/$', 'article.views.articles'),
    url(r'^get/(?P<article_id>\d+)/$', 'article.views.article'),
<<<<<<< HEAD
    url(r'^language/(?P<language>[a-z\-]+)/$', 'article.views.language'),
=======
>>>>>>> 347f063cefe0b889c1543b457ddb9de550edb957
    url(r'^create/$', 'article.views.create'),
    url(r'^like/(?P<article_id>\d+)/$', 'article.views.like_article'),
    url(r'^add_comment/(?P<article_id>\d+)/$', 'article.views.add_comment'),
    url(r'^delete_comment/(?P<comment_id>\d+)/$', 'article.views.delete_comment'),
    url(r'^search/$', 'article.views.search_titles'),
<<<<<<< HEAD
    url(r'^api/', include(article_resource.urls)),
=======
>>>>>>> 347f063cefe0b889c1543b457ddb9de550edb957

    
)

blog/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

from blog.forms import ContactForm1, ContactForm2, ContactForm3
from blog.views import ContactWizard
from django.conf import settings



urlpatterns = patterns('',
    (r'^articles/', include('article.urls')), # maps through to article Dir urls.py
    (r'^accounts/', include('userprofile.urls')),
    (r'^notification/', include('notification.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', 'blog.views.login'),
    url(r'^accounts/auth/$', 'blog.views.auth_view'),
    url(r'^accounts/logout/$', 'blog.views.logout'),
    url(r'^accounts/home/$', 'blog.views.home'),
    url(r'^accounts/invalid/$', 'blog.views.invalid_login'),
    url(r'^accounts/friend_requests/$', 'blog.views.friend_requests'),
    url(r'^accounts/friendship_accept/(?P<friendship_request_id>\d+)/$', 'blog.views.friendship_accept'),
    url(r'^accounts/friendship_reject/(?P<friendship_request_id>\d+)/$', 'blog.views.friendship_reject'),
    url(r'^accounts/friend_list/$', 'blog.views.friend_list'),
    #url(r'^accounts/follow/(?P<followee_id>\d+)/$', 'blog.views.follow'),
    url(r'^$', 'blog.views.register_user'),
    url(r'^accounts/register_success/$', 'blog.views.register_success'),
    url(r'contact/$', ContactWizard.as_view([ContactForm1, ContactForm2, ContactForm3])),
    url(r'^search/', include('haystack.urls')),
    
    
)



#

# when using include wrap using brackets instead of url keyword

django_test/article/urls.py
from django.conf.urls import patterns, include, url
from api import ArticleResource

article_resource = ArticleResource()


urlpatterns = patterns('',
    url(r'^all/$', 'article.views.articles'),
    url(r'^get/(?P<article_id>\d+)/$', 'article.views.article'),
    url(r'^language/(?P<language>[a-z\-]+)/$', 'article.views.language'),
    url(r'^create/$', 'article.views.create'),
    url(r'^like/(?P<article_id>\d+)/$', 'article.views.like_article'),
    url(r'^add_comment/(?P<article_id>\d+)/$', 'article.views.add_comment'),
    url(r'^delete_comment/(?P<comment_id>\d+)/$', 'article.views.delete_comment'),
    url(r'^search/$', 'article.views.search_titles'),
    url(r'^api/', include(article_resource.urls)),

    
)

django_test/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

from django_test.forms import ContactForm1, ContactForm2, ContactForm3
from django_test.views import ContactWizard

import settings

urlpatterns = patterns('',
    (r'^articles/', include('article.urls')), # maps through to article Dir urls.py
    (r'^accounts/', include('userprofile.urls')),
    (r'^notification/', include('notification.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', 'django_test.views.login'),
    url(r'^accounts/auth/$', 'django_test.views.auth_view'),
    url(r'^accounts/logout/$', 'django_test.views.logout'),
    url(r'^accounts/loggedin/$', 'django_test.views.loggedin'),
    url(r'^accounts/invalid/$', 'django_test.views.invalid_login'),
    url(r'^accounts/register/$', 'django_test.views.register_user'),
    url(r'^accounts/register_success/$', 'django_test.views.register_success'),
    url(r'contact/$', ContactWizard.as_view([ContactForm1, ContactForm2, ContactForm3])),
    url(r'^search/', include('haystack.urls')),
    url(r'^celery_test/', 'django_test.views.start_celery_task'),
    url(r'^celery_progress/', 'django_test.views.monitor_celery_task'),
)

if not settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    
    urlpatterns += staticfiles_urlpatterns()


# when using include wrap using brackets instead of url keyword

article/models.py
from django.db import models
from time import time
from approvals.models import Approval
from django.dispatch import receiver
from approvals.signals import article_approved
from django.db.models import signals
from django.conf import settings
from django_test import settings
from django.db.models.signals import post_save
import os.path
from whoosh.index import create_in, open_dir



import logging
logr = logging.getLogger(__name__)

def get_upload_file_name(instance, filename):
    return settings.UPLOAD_FILE_PATTERN % (str(time()).replace('.','_'), filename)

from django.contrib.auth.models import User
from time import time
from userprofile.models import UserProfile
from django.conf import settings
from blog import settings


def get_upload_file_name(instance, filename):
    return "assets/uploaded_files/%s_%s" % (str(time()).replace('.','_'), filename)

class Choice(models.Model):
    choice = models.CharField(max_length=300)
    
    def __unicode__(self):
        return self.choice

default_article_id = 1

class Article(models.Model):
    title = models.CharField(max_length= 200)
    body = models.TextField()
    pub_date = models.DateTimeField('date published')
    likes = models.IntegerField(default=0)
    thumbnail = models.FileField(upload_to=get_upload_file_name)
    approved = models.BooleanField(default=False)
    genre = models.ManyToManyField(Choice)
    user = models.ForeignKey(User, default=default_article_id)
    
    def __unicode__(self):
        return self.title

    
    def get_absolute_url(self):
        return "/articles/get/%i/" % self.id 
    

    
    def __unicode__(self):
        return self.title

@receiver(post_save, sender=Article)       
def create_approval_on_new_article(sender, **kwargs):
    if kwargs.get('created', False):
        approval = Approval.objects.create(article_id=kwargs.get('instance').id)
        logr.debug("Approval created: %s" % approval)


@receiver(article_approved)   
def approve_article(sender, **kwargs):
    a = Article.objects.get(id=kwargs.get('article_id'))
    a.approved = True
    a.save()
    logr.debug("Approved received")


class Comment(models.Model):
    name = models.CharField(max_length=200)
    body = models.TextField()
    pub_date = models.DateTimeField('date published')
    article = models.ForeignKey(Article) # links the to model functions together

    def get_thumbnail(self):
        thumb = str(self.thumbnail)
        if not settings.DEBUG:
            thumb = thumb.replace('assets/', '')
            
        return thumb 
    
    

class Comment(models.Model):
    body = models.TextField()
    pub_date = models.DateTimeField('date published')
    article = models.ForeignKey(Article) # links the to model functions together
    user = models.ForeignKey(User, default=default_article_id)
    
class Vote(models.Model):
    userprofile = models.ForeignKey(UserProfile)
    article = models.ForeignKey(Article)
    

article/forms.py
from django import forms
from models import Article, Comment

class ArticleForm(forms.ModelForm):

    class Meta:
        model = Article
<<<<<<< HEAD
        fields = ('title', 'body', 'thumbnail')
=======
        fields = ('title', 'body', 'thumbnail', 'genre')
        
>>>>>>> 347f063cefe0b889c1543b457ddb9de550edb957
       
class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
<<<<<<< HEAD
        fields = ('name', 'body')
=======
        fields = ('body',)
>>>>>>> 347f063cefe0b889c1543b457ddb9de550edb957
    

django_test/article/forms.py
from django import forms
from models import Article, Comment

class ArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        fields = ('title', 'body', 'thumbnail')
       
class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('name', 'body')
    

article/views.py
from django.shortcuts import render_to_response, get_object_or_404, render
from article.models import  Article, Comment
from django.http import HttpResponse
from forms import ArticleForm, CommentForm
from __future__ import absolute_import
from django.shortcuts import render_to_response, get_object_or_404, render
from .models import  Article, Comment, Vote
from django.http import HttpResponse
from .forms import ArticleForm, CommentForm
from django.http import HttpResponseRedirect
from django.core.context_processors import csrf
from django.utils import timezone
from haystack.query import SearchQuerySet # allows us to do searches within out views
from django.template import RequestContext # allos to pass info like message to one page to another -- unlike render_to_response
from django.contrib import messages
from django.conf import settings


from .tasks import hello_world

def articles(request):
    language = 'en-gb'
    session_language = 'en-gb'
    
    if 'lang' in request.COOKIES:
        language = request.COOKIES['lang']
    
    if 'lang' in request.session:
        session_language = request.session['lang']
        
    args = {}
    args.update(csrf(request))
    
    args['articles'] = Article.objects.all()
    args['language'] = language
    args['session_language'] = session_language
    hello_world.delay()
    
    return render(request,'articles.html', args)
                             
    
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from userprofile.models import UserProfile
from friendship.models import FriendshipRequest, Follow
from notification.models import General_notification


@login_required
def articles(request):
    
    genre_list = []
    follow_list = []
    articles_list = []
    userprofile = UserProfile.objects.get(user_id=request.user.id)
    genres = userprofile.genre.all()
    
    for items in genres:
        genre_list.append(items)
    
    f = Follow.objects.filter(follower=request.user)
    
    for users in f:
        follow_list.append(users.followee)
        
    genre_articles = Article.objects.all().filter(genre__in=genre_list)
    follower_articles = Article.objects.all().filter(user__in=follow_list) #__in filters through items in list
    top_ten_all = Article.objects.all().order_by('-likes')[:10]
    top_ten_personal = genre_articles[:10]
    
    for articles in genre_articles:
        articles_list.append(articles)
    
    for articles in follower_articles:
        articles_list.append(articles)
    
    args = {}
    args.update(csrf(request))
    
    args['articles'] = articles_list
    args['user'] = request.user
    args['genre'] = genres
    args['top_articles'] = top_ten_all
    args['top_articles_personal'] = top_ten_personal
    args['g_notification'] = General_notification.objects.all().filter(user=request.user, viewed=False)
    args['friend_request'] = FriendshipRequest.objects.all().filter(to_user=request.user)
    return render(request, 'articles.html', args)
                             
@login_required
def article(request, article_id):
    #x = get_object_or_404(Article, pk=article_id)
    #return render_to_response('article.html', {'article': x})

    return render(request, 'article.html',
                  {'article': Article.objects.get(id=article_id)})
    
    
def language(request, language='en-gb'):
    response = HttpResponse("setting language to %s" % language)
    
    response.set_cookie('lang', language)
    
    request.session['lang'] = language
    return response

    a = Article.objects.get(id=article_id)
    b = User.objects.get(id=a.user.id)
    c = request.user.username
    
    args = {}
    args.update(csrf(request))
    args['article'] = a
    args['people_profile'] = b
    args['un'] = c
    args['friend_request'] = FriendshipRequest.objects.all().filter(to_user=request.user)
    args['g_notification'] = General_notification.objects.all().filter(user=request.user, viewed=False)
    return render(request, 'article.html', args)
    
@login_required
def create(request):
    if request.POST:
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            c = form.save(commit=False) # saves form but doesn't enter it into the database
            c.pub_date = timezone.now()
            c.save()
            
            messages.success(request, "Your Article was added")

            c.user = request.user
            c.save()
            form.save_m2m()
            
            messages.add_message(request, messages.SUCCESS, "Your Article was added")

            
            return HttpResponseRedirect('/articles/all')
            
    else:
        form = ArticleForm()
        
    args = {}
    args.update(csrf(request))
    
    args['form'] = form

    
    return render_to_response('create_article.html', args)
    

    args['user'] = request.user
    args['g_notification'] = General_notification.objects.all().filter(user=request.user, viewed=False)
    args['friend_request'] = FriendshipRequest.objects.all().filter(to_user=request.user)
    return render_to_response('create_article.html', args)


 

def delete_comment(request, comment_id):
    c = Comment.objects.get(id=comment_id)
    
    article_id = c.article.id
    
    c.delete()
    

    messages.add_message(request,
                         settings.DELETE_MESSAGE,
                         "Your comment was deleted")
    
    return HttpResponseRedirect("/articles/get/%s" % article_id)
    
def like_article(request, article_id):
    if article_id:
        a = Article.objects.get(id=article_id)
        count = a.likes # put the number of likes into count
        count += 1 # add 1 to count
        a.likes = count # put the integer from count back into the likes
        a.save()
        
    return HttpResponseRedirect('/articles/get/%s' % article_id)
    

    messages.add_message(request, settings.DANGER_MESSAGE, "Comment Deleted")
    
    
    return HttpResponseRedirect("/articles/get/%s" % article_id)
 
   
def like_article(request, article_id):
    if article_id:
        a = Article.objects.get(id=article_id)
        article = Article.objects.get(id=article_id)
        userprofile = UserProfile.objects.get(user_id=request.user.id)
        
        vote, created = Vote.objects.get_or_create(
                            article=article,
                            userprofile=userprofile)
        
        if not created:
            return HttpResponseRedirect('/articles/get/%s' % article_id)
        else:
            count = a.likes # put the number of likes into count
            count += 1 # add 1 to count
            a.likes = count # put the integer from count back into the likes
            a.save()
            return HttpResponseRedirect('/articles/get/%s' % article_id)
        
        


@login_required   
def add_comment(request, article_id):
    a = Article.objects.get(id=article_id)
    
    if request.method == "POST":
        f = CommentForm(request.POST)
        if f.is_valid():
            c = f.save(commit=False) # saves form but doesn't enter it into the database
            c.pub_date = timezone.now()

            c.user = request.user

            c.article = a
            c.save()
            
            messages.success(request, "Your comment was added") # shorthand success message
        
            return HttpResponseRedirect('/articles/get/%s' % article_id)
        
    else:
		f = CommentForm()
	
		args = {}
		args.update(csrf(request))

		args['article'] = a
		args['form'] = f

		args['user'] = request.user
		args['friend_request'] = FriendshipRequest.objects.all().filter(to_user=request.user)
		args['g_notification'] = General_notification.objects.filter(user=request.user, viewed=False)
		return render_to_response('add_comment.html', args)
		
def search_titles(request):
    articles = SearchQuerySet().autocomplete(content_auto=request.POST.get('search_text', ''))

    return render_to_response('ajax_search.html', {'articles' : articles})
    

    

article/templates/add_comment.html
{% extends "base.html" %}
<<<<<<< HEAD

{% block sidebar %}
<ul>
	<li><a href="/articles/get/{{article.id}}">Cancel</a></li>
</ul>
{% endblock %}
			
{% block content %}

<form action="/articles/add_comment/{{article.id}}/" method="post">{% csrf_token %}
<ul>
{{form.as_ul}}
</ul>

<input type="submit" name="submit" value="Post Comment">
</form>
=======
{% load bootstrap_toolkit %}

			
{% block content %}

<div class="blog-header">
	<h1 class="blog-title">Add Comment</h1>
</div>

<div class="row">

<div class="col-sm-8 blog-main">
	<form action="/articles/add_comment/{{article.id}}/" method="post">{% csrf_token %}
		<ul>
			{{form|as_bootstrap}}
		</ul>

		<input type="submit" name="submit" value="Post Comment">
	</form>

</div> <!-- main -->

</div> <!-- row -->
>>>>>>> 347f063cefe0b889c1543b457ddb9de550edb957

{% endblock %}

article/templates/ajax_search.html
{% if articles.count > 0 %}

{% for article in articles %}
    <li><a href="{{ article.object.get_absolute_url }}">{{ article.object.title }}</a></li>
{% endfor %}

{% else %}

<li>None to show!</li>

{% endif %}

article/templates/article.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{article.title}}{% endblock %}

<<<<<<< HEAD
{% block sidebar %}
<ul>
	<li><a href="/articles/all">Articles</a></li>
</ul>
{% endblock %}
			
{% block content %}

<h1>{{article.title}}</h1> <!-- variables use curly brackets -->
<p>{{article.body}}</p>
=======
			
{% block content %}

<div class="blog-header">
	<h1 class="blog-title">{{article.title}} <p class="lead blog-description">{% for items in article.genre.all %} {{items}}. {% endfor %}</p></h1>
	<p class="lead blog-description">{{article.pub_date}} by {% if article.user == people_profile.username %}
<a href="/accounts/home">{{article.user}}</a>

{% else %}
<a href="/accounts/user/{{article.user.id}}">{{article.user}}</a>
</p>
{% endif %}
</div>
      
<div class="row">

<div class="col-sm-8 blog-main">
    {{article.body}}
>>>>>>> 347f063cefe0b889c1543b457ddb9de550edb957

{% if article.thumbnail %}
<p><img src="{% get_static_prefix %}{{article.get_thumbnail}}" width="200"/></p>
{% endif %}

<<<<<<< HEAD
<p>{{article.likes}} People liked this article</p>
=======
<p><span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span> {{article.likes}} People liked this article</p>
>>>>>>> 347f063cefe0b889c1543b457ddb9de550edb957
<p><a href="/articles/like/{{article.id}}">Like</a></p>

<h2>Comments</h2>
{% for c in article.comment_set.all %} <!-- tells django that article is related to comment -->
<<<<<<< HEAD
<h3>{{c.name}}</h3>
<p>{{c.body}}</p>
<a href="/articles/delete_comment/{{c.id}}">Delete</a>
=======
<h3>{% if c.user == people_profile.username %}
<a href="/accounts/home">{{c.user}}</a>
{% else %}
<a href="/accounts/user/{{c.user.id}}">{{c.user}}</a>
{% endif %}
</h3>
<p>{{c.body}}</p>
{% if un == c.user.username %}<a href="/articles/delete_comment/{{c.id}}">Delete</a>{% endif %}
>>>>>>> 347f063cefe0b889c1543b457ddb9de550edb957
{% endfor %}

<p><a href="/articles/add_comment/{{article.id}}">Add Comment</a></p>

<<<<<<< HEAD
=======
</div> <!-- main -->

</div> <!-- row -->



>>>>>>> 347f063cefe0b889c1543b457ddb9de550edb957
{% endblock %}

article/templates/articles.html
{% extends "base.html" %}
<<<<<<< HEAD
{% load article_tags %}

{% block sidebar %}
<ul>
    <li><a href="/articles/all">Articles</a></li>
    <li><a href="/articles/create">Create Article</a></li>

</ul>

<h3>Search</h3>
{% csrf_token %}
<input type="text" id="search" name="search" />

<ul id="search-results">

</ul>



{% endblock %}




{% block title %}Articles{% endblock %}

{% block content %}

<h2>Language is: {{language}}</h2>

<h2>Session Language is: {{session_language}}</h2>

{% if articles %}
    
        {% for article in articles %}
            {% if article.approved %}
            <div>
				<h2><a href="/articles/get/{{article.id}}/">{{article.title}}</a></h2>
				<p>{{  article.body|article_shorten_body:50 }}</p> <!-- add filters using a pipe -->
				<!-- if filter has extra parameters ie. 'truncate words' colon and then specifications-->
				<p>{{article.likes}} People liked this article</p>
            </div>
            {% endif %}
        {% endfor %} <!-- logic (python) curly brace and percent sign -->
    

{% else %} <!-- place holder to tell python when to finsh. because there is no indentation-->
    <p>No articles in database</p>
{% endif %}
=======


{% block content %}

     <div class="blog-header">
        <h1 class="blog-title">Articles</h1>
      </div>
      
<div class="row">

 <div class="col-sm-8 blog-main">
    {% if articles %}
    
        {% for article in articles %}
          <div class="blog-post">
            <h2 class="blog-post-title"><a href="/articles/get/{{article.id}}">{{article.title}}</a></h2>
            <p class="blog-post-meta">{% for items in article.genre.all %} {{items}}. {% endfor %} – <a href="/accounts/user/{{article.user.id}}/">{{article.user}}</a></p>

            <p>{{article.body|lower|truncatewords:50}}</p>
          </div><!-- /.blog-post -->
          {% endfor %}
          
          {% else %}
			<p>No Article to Show</p>
			{% endif %}

  

        </div><!-- /.blog-main -->



<div class="col-sm-3 col-sm-offset-1 blog-sidebar">
        
          <div class="sidebar-module sidebar-module-inset">
            <h4 style="text-align: center;">Top 10 All Categories</h4>
            <ol class="list-unstyled">
              {% if top_articles %}
              {% for articles in top_articles %}
              <li style="text-align:center;"><a href="/articles/get/{{articles.id}}/">{{articles.title}}</a></li>
              <li class="divider"></li>
              {% endfor %}
              {% else %}
              <p> Error </p>
              {% endif %}
              
              </br>
               
            <h4 style="text-align: center;">Top 10 {{user.username}} Categories</h4>
            <ol class="list-unstyled">
              {% if top_articles_personal %}
              {% for articles in top_articles_personal %}
              <li style="text-align:center;"><a href="/articles/get/{{articles.id}}/">{{articles.title}}</a></li>
              <li class="divider"></li>
              {% endfor %}
              {% else %}
              <p> Error </p>
              {% endif %}
              
              
            </ol>
          </div>
</div><!-- /.blog-sidebar -->

</div> <!-- row -->
>>>>>>> 347f063cefe0b889c1543b457ddb9de550edb957

{% endblock %}

article/templates/create_article.html
{% extends "base.html" %}
<<<<<<< HEAD
=======
{% load bootstrap_toolkit %}
>>>>>>> 347f063cefe0b889c1543b457ddb9de550edb957

{% block sidebar %}
<ul>
    <li><a href="/articles/all">Cancel</a></li>
</ul>
{% endblock %}

{% block content %}

<form action="/articles/create/" method="post" enctype="multipart/form-data">{% csrf_token %}
<<<<<<< HEAD
{{ form }}
=======
{{ form|as_bootstrap }}
>>>>>>> 347f063cefe0b889c1543b457ddb9de550edb957

<input type="submit" name="submit" value="Crete Article">

</form>

{% endblock %}